set_project("blook")
add_requires("gtest 1.17.0")
set_languages("cxx23")
set_arch("x64")
set_defaultmode("releasedbg")
add_rules("mode.debug", "mode.releasedbg", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})

rule("blook.masm")
    set_extensions(".asm")
    on_build_file(function (target, sourcefile, opt)
        import("core.project.depend")
        import("core.tool.toolchain")
        local tc = toolchain.load("msvc", {plat = target:plat(), arch = target:arch()})
        local compiler = tc:tool("as")
        local objectfile = target:objectfile(sourcefile)
        table.insert(target:objectfiles(), objectfile)
        depend.on_changed(function ()
            os.mkdir(path.directory(objectfile))
            os.vrunv(compiler, {"/nologo", "/c", "/Fo" .. objectfile, sourcefile}, {envs = tc:runenvs()})
        end, {dependfile = target:dependfile(objectfile), files = {sourcefile}, changed = target:is_rebuilt()})
    end)
rule_end()

target("blook-drv")
    add_rules("wdk.driver", "wdk.env.wdm", "blook.masm")
    set_values("wdk.env.winver", "win10_vb")
    set_exceptions("no-cxx")
    add_defines("NOMINMAX", "POOL_NX_OPTIN=1")
    add_includedirs("src", "third_party/ia32")
    add_files("src/driver/*.cc", "src/driver/hide/*.cc", "src/driver/hv/*.cpp", "src/driver/hv/*.asm")
    add_cxxflags("/kernel", "/GR-", "/EHs-c-", "/Zc:threadSafeInit-", "/GS-", "/utf-8", {force = true})
    add_syslinks("ntoskrnl", "hal", "wmilib", "wdmsec")
    add_ldflags("/INTEGRITYCHECK", "/ENTRY:DriverEntry", {force = true})

target("blook-loader")
    set_kind("binary")
    add_defines("NOMINMAX", "UNICODE", "_UNICODE")
    add_files("src/loader/*.cc")
    add_cxxflags("/utf-8", "/permissive-", "/W4", {tools = "cl"})
    add_includedirs("src")
    add_syslinks("advapi32")

target("blook-tests")
    set_kind("binary")
    add_packages("gtest")
    add_files("tests/unit.cc", "tests/ept/*.cc", "tests/ept_edges/*.cc", "src/driver/hv/ept.cpp", "src/driver/hv/mtrr_policy.cpp")
    add_includedirs("tests")
    add_defines("BLOOK_EPT_TEST")
    add_includedirs("third_party/ia32")
    add_includedirs("src")
    add_tests("unit")

-- Opt-in real-driver GoogleTests; never run as part of the host-only suite.
target("blook-ept-live-tests")
    set_kind("binary")
    set_default(false)
    add_packages("gtest")
    add_files("tests/ept_live/*.cc", "tests/ept/main.cc")
    add_includedirs("src")
    add_defines("NOMINMAX", "UNICODE", "_UNICODE")
    add_cxxflags("/utf-8", "/permissive-", "/W4", {tools = "cl"})

-- Fast host-only contracts: these do not open the driver or run virtualization.
for _, suite in ipairs({"client", "loader", "protocol"}) do
    target("blook-" .. suite .. "-tests")
        set_kind("binary")
        add_defines("NOMINMAX", "UNICODE", "_UNICODE")
        add_packages("gtest")
        add_files("tests/" .. suite .. ".cc", "tests/ept/main.cc")
        add_includedirs("src")
        add_cxxflags("/utf-8", "/permissive-", "/W4", {tools = "cl"})
        add_tests("unit")
end

target("blook-terminal-fixture")
    set_kind("binary")
    set_default(false)
    add_defines("NOMINMAX", "UNICODE", "_UNICODE")
    add_packages("gtest")
    add_files("tests/terminal.cc", "src/loader/terminal.cc", "tests/ept/main.cc")
    add_tests("unit")
    add_includedirs("src")
    add_cxxflags("/utf-8", "/permissive-", "/W4", {tools = "cl"})

target("blook-ept-smoke")
    set_kind("binary")
    set_basename("blook-ept-smoke")
    add_defines("NOMINMAX", "UNICODE", "_UNICODE")
    add_packages("gtest")
    add_files("tests/smoke.cc", "tests/ept_live/fixture.cc", "tests/ept/main.cc")
    add_includedirs("src")

-- Real-driver lifecycle regression; never part of the host-only test suite.
target("blook-session-smoke")
    set_kind("binary")
    set_default(false)
    add_defines("NOMINMAX", "UNICODE", "_UNICODE")
    add_packages("gtest")
    add_files("tests/session_smoke.cc")
    add_includedirs("src")
    add_cxxflags("/utf-8", "/permissive-", "/W4", {tools = "cl"})

target("blook-live-watch")
    set_kind("binary")
    set_default(false)
    add_defines("NOMINMAX", "UNICODE", "_UNICODE")
    add_packages("gtest")
    add_files("tests/live_watch.cc", "tests/ept_live/fixture.cc", "tests/ept/main.cc")
    add_includedirs("src")
    add_cxxflags("/utf-8", "/permissive-", "/W4", {tools = "cl"})

target("blook-live-cow")
    set_kind("binary")
    set_default(false)
    add_defines("NOMINMAX", "UNICODE", "_UNICODE")
    add_packages("gtest")
    add_files("tests/live_cow.cc", "tests/ept_live/fixture.cc", "tests/ept/main.cc")
    add_includedirs("src")
    add_cxxflags("/utf-8", "/permissive-", "/W4", {tools = "cl"})

target("blook-live-dormant")
    set_kind("binary")
    set_default(false)
    add_defines("NOMINMAX", "UNICODE", "_UNICODE")
    add_packages("gtest")
    add_files("tests/live_dormant.cc", "tests/ept_live/fixture.cc", "tests/ept/main.cc")
    add_includedirs("src")
    add_cxxflags("/utf-8", "/permissive-", "/W4", {tools = "cl"})

target("blook-image-page-tests")
    set_kind("binary")
    set_default(false)
    add_packages("gtest")
    add_defines("NOMINMAX", "UNICODE", "_UNICODE")
    add_files("tests/image_page.cc", "tests/ept/main.cc")
    add_includedirs("src")
    add_syslinks("bcrypt")
    add_cxxflags("/utf-8", "/permissive-", "/W4", {tools = "cl"})

target("blook-bench")
    set_kind("binary")
    add_defines("NOMINMAX", "UNICODE", "_UNICODE")
    add_files("tests/bench.cc")
    add_includedirs("src")
